name: "Quality Assurance 🔍"

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.x
      - name: Setup Yarn
        uses: actions/cache@v3.0.5
        with:
          path: node_modules
          key: yarn-cache-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: yarn-cache-
      - run: yarn install --immutable
      - run: yarn check-dependencies
      - run: yarn typecheck
      - run: yarn test --ci
      - run: yarn lint
